### ISSUE TITLE
git folder not found if on a subpath

### ISSUE THREAD

**Issue by notdodo** [davtur19/DotGit#8]
Hi!

It's seems that the extension is not able to detect a `.git` folder if is a subpath.

For example the site <https://fossies.org/> has a `.git` folder on the path `https://fossies.org/linux/knock/.git/logs/HEAD`

**Comment by davtur19** [comment]
Hi,

It is intended behavior, because otherwise the extension would have to make too many requests.

It would mean making a request every time the browser makes a request, so the browser has to double the requests, and it would slow down the browser a lot.

Alternatively I could save the requests already made so as not to repeat them (as already happens for domains), but in any case they would still be almost double the requests, in addition to occupying a lot of memory and saving sensitive data.

So the best solution I think is not to implement such a thing, as it should be quite rare to find a .git into a subdirectory.

**Comment by notdodo** [comment]
Hi!

I understand the problem and thank you for the explanation although is not that rare (i.e. reverse proxy to multiple apps or plugins/dependencies used in the webapp, a simple google dork can help you find them).

Anyway I don't want to force you to implement this, your choice :)

EDIT: maybe a switch to enable/disable this feature?

**Comment by davtur19** [comment]
If I put a switch, it wouldn't be something you should normally use while using the browser, you should only use it on a specific site, and at this point it would make more sense to use a dirscan tool.
